apiVersion: v1
kind: PersistentVolume
metadata:
  name: django-pv
  namespace: django
spec:
  storageClassName: "gp2"
  capacity:
   storage: 5Gi
  accessModes:
   - ReadWriteOnce
  hostPath:
    path: "/mnt/data"