apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: django-pv
  namespace: django
spec:
  storageClassName: "" # Empty string must be explicitly set otherwise default StorageClass will be set
  volumeName: django-pv
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce  
  resources:
    requests:
      storage: 5Gi